dist: xenial
language: python
python:
  - "3.7"  

env:
  - DACE_optimizer_automatic_strict_transformations=1
  - DACE_optimizer_automatic_strict_transformations=0

# Dependencies
before_install:
  - sudo apt-get install libyaml-dev cmake

install:
  - pip install ".[test]" .
  - pip install coverage codecov
  - pip install tensorflow==1.15.0

script:
  - export NOSTATUSBAR=1
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - export COVERAGE_RCFILE=`pwd`/.coveragerc
  - export PYTHON_BINARY="coverage run --source=`pwd`/dace --parallel-mode"
  - ./test_all.sh
  - cd tests; coverage combine . */; coverage report; coverage xml

after_success:
  - codecov
